services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: crime_user
      POSTGRES_PASSWORD: crime_pass
      POSTGRES_DB: crime_analytics
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../db/postgres_init.sql:/docker-entrypoint-initdb.d/init.sql

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  nimbus:
    image: storm:latest
    container_name: storm_nimbus
    command: storm nimbus
    depends_on:
      - zookeeper
    environment:
      - STORM_ZOOKEEPER_SERVERS=zookeeper
    ports:
      - "6627:6627"

  supervisor:
    image: storm:latest
    container_name: storm_supervisor
    command: storm supervisor
    depends_on:
      - nimbus
      - zookeeper
    environment:
      - STORM_ZOOKEEPER_SERVERS=zookeeper
      - STORM_NIMBUS_HOST=nimbus

  ui:
    image: storm:latest
    container_name: storm_ui
    command: storm ui
    depends_on:
      - nimbus
    environment:
      - STORM_ZOOKEEPER_SERVERS=zookeeper
      - STORM_NIMBUS_HOST=nimbus
    ports:
      - "8080:8080"

  spark:
    build:
      context: .
      dockerfile: Dockerfile.spark
    container_name: spark
    environment:
      - SPARK_MODE=master
    ports:
      - "8081:8080"
      - "7077:7077"
    volumes:
      - ../spark:/opt/spark/app
      - ../config:/opt/spark/app/config
      - ../data:/opt/spark/app/data
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master

volumes:
  postgres_data:
  mongo_data:
